language: python
sudo: false

branches:
  only:
    - master

install:
  - source devtools/travis-ci/install_miniconda.sh
  - export PYTHONUNBUFFERED=true
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --add channels conda-forge

script:
  # adapted from pymbar
  # Add org channel
  - conda config --add channels ${ORGNAME}
  # Create a test environment
  - conda create --quiet --yes -n test python=$python
  # Activate the test environment
  - source activate test
  # Build recipie
  - conda build devtools/conda-recipe
  # Install locally-built package
  - conda install --yes --quiet --use-local ${PACKAGENAME}
  #- conda install --yes --quiet pip nose nose-timer
  # Test the package
  #- cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=2 --with-doctest --with-timer && cd ..

os:
  - osx
  - linux
  - windows

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35
    - python=3.6  CONDA_PY=36
  global:
    - PACKAGENAME="toyNN"
    - ORGNAME="kam_haider"

after_success:
  - source devtools/travis-ci/deploy_anaconda.sh