package:
  name: toyNN
  version: 1.0.0

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy >=1.11

test:
  requires:
    - pytest
  imports:
    - toyNN
  commands:
    - python -m pytest toyNN

about:
  home: https://github.com/kamran-haider/toyNN
  license: MIT
  summary: A bare-bones Python implementation of deep learning neural networks.
